// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upsjcizauzeflbpsyxsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwc2pjaXphdXplZmxicHN5eHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MzkyMDMsImV4cCI6MjA1NDMxNTIwM30.K8PD0baeKTHA73iPwEOO4hJ-m9GDES5KHAJROR8jJVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);